# Futong-Itgo-Monitor-Agent Global Configuration

# logger configuration
log:
  level: "debug"
  stdout: true
  logfile: "run.log"
  logMaxDays: 7

confWeb:
  getConfUrl : "http://172.16.71.20:8001/api/conf"
